### ISSUE TITLE
Raise IOError/FileNotFoundError if glob returns empty list but URL is not XRootD path 

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fast-curator#17]
Currently, when passing POSIX paths with wildcards to `fast_carpenter`, it will attempt to load the XROOTD path if glob does not find any files.

Instead, it might be useful to check for an XrootD URL (i.e. starting with `root://`) and raise an IOError or FileNotFoundError if the POSIX path contains no files.

**Comment by benkrikler** [comment]
Since #18 this is partially addressed by a user being able to force that files are "local" files.  I'm not sure about the error throwing aspect of this request being addressed though, so I'll leave this open for now.

**Comment by wctaylor** [comment]
I came across this issue as well. I modified the `glob` function in `xrootd_glob.py`  to look like this:

```
def glob(pathname):
    # Let normal python glob try first
    try_glob = gl.glob(pathname)
    if try_glob:
        return try_glob
    # If pathname does not contain a wildcard:
    if not gl.has_magic(pathname):
        return [pathname]
    ### Add this to fix
    else:
        base_path = pathname.split('*')[0]
        if not os.path.exists(base_path):
            raise FileNotFoundError("Path to files does not exist")
    ### End of fix
    # Else try xrootd instead
    return xrootd_glob(pathname)
```

If this is an acceptable fix, I can create a pull request

**Comment by benkrikler** [comment]
For a while now we've been depending on the version of xrootd_glob that we added to the official xrootd python bindings.  That was reviewed by the XRootd developers themselves, and as a result has some better error checking than the original version we developed in here.  I'm going to close this for now as a result but if you hit this problem again, feel free to re-open this issue!
