### ISSUE TITLE
Allow to disable defaults in output file

### ISSUE THREAD

**Issue by alexander-held** [FAST-HEP/fast-curator#38]
The automatic identification of common options in the output YAML is very convenient to keep the output compact. For debugging purposes, it would be convenient to allow disabling this feature that sets defaults (via a command line argument). Instead, every option then would always be explicitly written. 

This seems not too difficult to add, I can have a look and prepare a PR.

**Comment by benkrikler** [comment]
This has been implemented in #39 so I'm closing this off.
